### ISSUE TITLE
[doc] explain truss input file format in documentation

### ISSUE THREAD

**Issue by yijiangh** [JuliaTopOpt/TopOpt.jl#138]

**Comment by pitipatw** [comment]
I made a json file to input data from Grasshopper through WebSockets to Julia. 
I think I might able to help on this

**Comment by yijiangh** [comment]
@pitipatw That's awesome! The corresponding page in our doc is [here](https://juliatopopt.github.io/TopOpt.jl/dev/examples/problem/#D-and-3D-truss-problem-from-json-file) and the source [here](https://github.com/JuliaTopOpt/TopOpt.jl/blob/master/docs/src/literate/problem.jl#L93).

In case you are not familiar with doc generation in Julia, we use [Documentor.jl](https://documenter.juliadocs.org/stable/) for building the docs (from markdown to HTML files), and we have a [make.jl](https://github.com/JuliaTopOpt/TopOpt.jl/blob/master/docs/make.jl) file for triggering the generation.
We also use [Literate.jl](https://fredrikekre.github.io/Literate.jl/v2/) for turning a `.jl` file directly into an example documentation. If the comments you write in the example script follows markdown syntax, it will be compiled into a nicely looking webpage with all the outputs rendered (like what you would see in a jupyter notebook). 
@pitipatw, I would suggest that you start by adding some comments on the JSON keys and value format in our truss file in the source file [here](https://github.com/JuliaTopOpt/TopOpt.jl/blob/master/docs/src/literate/problem.jl#L104-L109). And maybe remove the `print(JSON.json(f, 2));` - I think it is occupying too much space on the doc page.

**Comment by pitipatw** [comment]
Copied.
